// Generated by CoffeeScript 1.9.3
(function() {
  var data, expr, graph, jref, template;

  jref = require('json-ref-lite');

  expr = require('property-expr');

  data = {
    boss: {
      name: "John"
    },
    employee: {
      name: "Matt"
    }
  };

  template = jref.resolve({
    boss: {
      name: "{boss.name}"
    },
    employee: {
      name: "{#/employee/name}"
    },
    names: [
      {
        "$ref": "#/boss/name"
      }, {
        "$ref": "#/employee/name"
      }
    ]
  });

  graph = jref.evaluate(template, data);

  console.log(JSON.stringify(graph, null, 2));

}).call(this);
