// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function() {
    this.findIds = function(json, ids) {
      var id, k, obj, v;
      id = false;
      obj = {};
      for (k in json) {
        v = json[k];
        if (json.id != null) {
          id = json.id;
        }
        if (id && k !== "id") {
          obj[k] = v;
        }
        if (typeof v === 'object') {
          this.findIds(v, ids);
        }
      }
      if (id) {
        return ids[id] = obj;
      }
    };
    this.replace = function(json, ids) {
      var k, results, v;
      results = [];
      for (k in json) {
        v = json[k];
        if ((v['$ref'] != null) && (ids[v['$ref']] != null)) {
          results.push(json[k] = ids[v['$ref']]);
        } else {
          if (typeof v === 'object') {
            results.push(this.replace(v, ids));
          } else {
            results.push(void 0);
          }
        }
      }
      return results;
    };
    this.resolve = function(json) {
      var ids;
      ids = {};
      this.findIds(json, ids);
      this.replace(json, ids);
      return json;
    };
    return this;
  };

}).call(this);
